imports:
    - resource: "sylius_crud.yml"

positibe_user:
    roles: [ROLE_EDITOR]

parameters:
    positibe.menu_node.class: Positibe\Bundle\CmsBundle\Entity\MenuNode

assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

cmf_core:
    persistence:
        orm: ~
    publish_workflow:
        request_listener: true

cmf_seo:
    title: seo.title
    description: seo.description
    persistence:
        orm:
    sitemap:
        enabled: true
    alternate_locale:
        provider_id: positibe_cms.alternate_locale_provider

positibe_cms:
    content_class: [Positibe\Bundle\CmsBundle\Entity\Page, Positibe\Bundle\CmsBundle\Entity\Category ]

cmf_routing:
    dynamic:
        controllers_by_class:
            # the order here matter
            Positibe\Bundle\CmsBundle\Entity\Category: PositibeCmsBundle:Default:categoryIndex
            Positibe\Bundle\CmsBundle\Entity\Page: PositibeCmsBundle:Default:index
#            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction
        limit_candidates: 1
        match_implicit_locale: false

sonata_block:
    default_contexts: ~
    blocks:
        positibe_cms.pages_by_category: ~
        positibe_cms.featured_page: ~

lunetics_locale:
    allowed_locales: "%locales%"
    guessing_excluded_pattern: ^/css|^/js|^/admin|^/_wdt|^/_profiler|^/_error
    guessing_order:
        - query
        - session
        - router
#    switcher:
#        use_controller: true                # Must be set to true if you want to use the controller. Defaults to false
#        use_referrer: true                  # Redirect to the origin url from where the switcher was used. Defaults to true
#        redirect_to_route: homepage   # This parameter MUST be set. Fallback route if no referrer could be found.
#        redirect_statuscode: 302            # Redirect HTTP status code. Options:  300, 301, 302, 303, 307. Defaults to 302

framework:
    workflows:
        publishable:
            type: 'state_machine' # or 'workflow'
            marking_store:
                type: 'single_state' # or 'multiple_state'
                arguments:
                    - 'state'
            supports:
                - Positibe\Bundle\CmsBundle\Entity\Page
            places:
                - draft
                - published
                - unpublished
            transitions:
                publish:
                    from: draft
                    to:   published
                unpublish:
                    from: published
                    to:   unpublished
                republish:
                    from: unpublished
                    to:   published
ivory_ck_editor:
    configs:
        content:
            toolbar: standard
            filebrowserUploadRoute: "positibe_media_upload"
            filebrowserBrowseRoute: "elfinder"
            contentsCss: "css/compiled/main.css"

fm_elfinder:
    instances:
        default:
            locale: "%locale%" # defaults to current request locale
            editor: ckeditor # other choices are tinymce or simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/gif','image/gif','image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 8M