imports:
    - resource: "sylius_crud.yml"

parameters:
    positibe.menu_node.class: Positibe\Bundle\CmsBundle\Entity\MenuNode

cmf_core:
    persistence:
        orm: ~
    publish_workflow:
        request_listener: true

cmf_seo:
    title: %%content_title%%
    description: %%content_description%%
    persistence:
        orm:

positibe_menu:
    content_class: [Positibe\Bundle\CmsBundle\Entity\Page, Positibe\Bundle\CmsBundle\Entity\Category ]

positibe_cmf_routing_extra:
    auto_routing:
        Positibe\Bundle\CmsBundle\Entity\Page:
#            uri_schema: /{category}/{title}
            uri_schema: /{title}
            token_providers:
#                category: [content_method, { method: getCategoryName }]
                title: [content_method, { method: getTitle }]
        Positibe\Bundle\CmsBundle\Entity\Category:
            uri_schema: /{title}
            token_providers:
                title: [content_method, { method: getTitle }]

cmf_routing:
    dynamic:
        controllers_by_class:
            # the order here matter
            Positibe\Bundle\CmsBundle\Entity\Category: PositibeCmsBundle:Default:categoryIndex
            Positibe\Bundle\CmsBundle\Entity\Page: PositibeCmsBundle:Default:index
#            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction

sonata_block:
    default_contexts: ~

framework:
    workflows:
        publishable:
            type: 'state_machine' # or 'workflow'
            marking_store:
                type: 'single_state' # or 'multiple_state'
                arguments:
                    - 'state'
            supports:
                - Positibe\Bundle\CmsBundle\Entity\Page
            places:
                - draft
                - published
                - unpublished
            transitions:
                publish:
                    from: draft
                    to:   published
                unpublish:
                    from: published
                    to:   unpublished
                republish:
                    from: unpublished
                    to:   published
#ivory_ck_editor:
#    configs:
#        default:
#            toolbar: standard
#            filebrowserUploadRoute: "cmf_media_upload"
#            filebrowserBrowseRoute: "elfinder"
#            skin: "../../positibecmf/ckeditor/skins/office2013"

#fm_elfinder:
#    locale: %locale% # defaults to current request locale
#    editor: ckeditor # other choices are tinymce or simple
#    showhidden: false # defaults to false
#    fullscreen: true # defaults true, applies to simple and ckeditor editors
#    include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
#    compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
#    connector:
#        debug: false # defaults to false
#        roots:       # at least one root must be defined
#            uploads:
#                driver: LocalFileSystem
#                path: uploads
#                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
#                upload_deny: ['all']
#                upload_max_size: 2M