imports:
    - resource: "sylius_crud.yml"

parameters:
    positibe.menu_node.class: Positibe\Bundle\CmsBundle\Entity\MenuNode

assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

cmf_core:
    persistence:
        orm: ~
    publish_workflow:
        request_listener: true

cmf_seo:
    title: "%%content_title%%"
    description: "%%content_description%%"
    persistence:
        orm:

positibe_menu:
    content_class: [Positibe\Bundle\CmsBundle\Entity\Page, Positibe\Bundle\CmsBundle\Entity\Category ]

cmf_routing:
    dynamic:
        controllers_by_class:
            # the order here matter
            Positibe\Bundle\CmsBundle\Entity\Category: PositibeCmsBundle:Default:categoryIndex
            Positibe\Bundle\CmsBundle\Entity\Page: PositibeCmsBundle:Default:index
#            Symfony\Cmf\Bundle\RoutingBundle\Doctrine\Phpcr\RedirectRoute:  cmf_routing.redirect_controller:redirectAction

sonata_block:
    default_contexts: ~

lunetics_locale:
    allowed_locales: "%locales%"
    guessing_excluded_pattern: ^/css|^/js|^/admin|^/_wdt|^/_profiler|^/_error
    guessing_order:
        - query
        - router

framework:
    workflows:
        publishable:
            type: 'state_machine' # or 'workflow'
            marking_store:
                type: 'single_state' # or 'multiple_state'
                arguments:
                    - 'state'
            supports:
                - Positibe\Bundle\CmsBundle\Entity\Page
            places:
                - draft
                - published
                - unpublished
            transitions:
                publish:
                    from: draft
                    to:   published
                unpublish:
                    from: published
                    to:   unpublished
                republish:
                    from: unpublished
                    to:   published
ivory_ck_editor:
    configs:
        content:
            toolbar: standard
            filebrowserUploadRoute: "positibe_media_upload"
            filebrowserBrowseRoute: "elfinder"
            contentsCss: "css/compiled/main.css"

fm_elfinder:
    instances:
        default:
            locale: "%locale%" # defaults to current request locale
            editor: ckeditor # other choices are tinymce or simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/gif','image/gif','image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 8M