admin_cms:
    path: /
    defaults: { _controller: "FrameworkBundle:Template:template", template: "PositibeCmsBundle::index.html.twig"}

positibe_cache_block:
    resource: "@PositibeCmsBundle/Resources/config/routing/block_cache.yml"

positibe_admin_menu:
    resource: "@PositibeCmsBundle/Resources/config/routing/menu.yml"

positibe_admin_menu_node:
    resource: "@PositibeCmsBundle/Resources/config/routing/menu_node.yml"
#
positibe_admin_menu_node_children:
    resource: "@PositibeCmsBundle/Resources/config/routing/menu_node_children.yml"

positibe_admin_page:
    resource: "@PositibeCmsBundle/Resources/config/routing/page.yml"

positibe_admin_category:
    resource: "@PositibeCmsBundle/Resources/config/routing/category.yml"

positibe_admin_block:
    resource: "@PositibeCmsBundle/Resources/config/routing/block.yml"

positibe_admin_menu_block:
    resource: "@PositibeCmsBundle/Resources/config/routing/menu_block.yml"

positibe_admin_gallery_block:
    resource: "@PositibeCmsBundle/Resources/config/routing/gallery_block.yml"

positibe_admin_content_block:
    resource: "@PositibeCmsBundle/Resources/config/routing/content_block.yml"

positibe_admin_page_block:
    resource: "@PositibeCmsBundle/Resources/config/routing/page_block.yml"

positibe_admin_multimedia:
    resource: "@PositibeMediaBundle/Resources/config/multimedia_routing.yml"

positibe_website:
    resource: "@PositibeCmsBundle/Resources/config/routing/website.yml"

positibe_admin_page_iframe:
    path: /page_iframe/{id}
    defaults: {_controller: "PositibeCmsBundle:Default:iframe" }

positibe_admin_menu_content_class:
    path: /positibe-menu-content-class
    defaults: {_controller: PositibeCmsBundle:Menu:getContentForm }

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"

positibe_cache_apc_clear:
    path: /positibe/clear_cache/{token}
    defaults: { _controller: positibe.cache.apc:cacheAction }