positibe_cache_block:
    resource: "@PositibeContentBundle/Resources/config/routing/block_cache.yml"

positibe_admin_menu:
    resource: "@PositibeContentBundle/Resources/config/routing/menu.yml"

positibe_admin_menu_node:
    resource: "@PositibeContentBundle/Resources/config/routing/menu_node.yml"
#
positibe_admin_menu_node_children:
    resource: "@PositibeContentBundle/Resources/config/routing/menu_node_children.yml"

positibe_admin_page:
    resource: "@PositibeContentBundle/Resources/config/routing/page.yml"

positibe_admin_category:
    resource: "@PositibeContentBundle/Resources/config/routing/category.yml"

positibe_admin_block:
    resource: "@PositibeContentBundle/Resources/config/routing/block.yml"

positibe_admin_menu_block:
    resource: "@PositibeContentBundle/Resources/config/routing/menu_block.yml"

positibe_admin_gallery_block:
    resource: "@PositibeContentBundle/Resources/config/routing/gallery_block.yml"

positibe_admin_content_block:
    resource: "@PositibeContentBundle/Resources/config/routing/content_block.yml"

positibe_admin_page_block:
    resource: "@PositibeContentBundle/Resources/config/routing/page_block.yml"