services:
    positibe_cms.guard_listener:
        class: Positibe\Bundle\CmsBundle\Workflow\GuardListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }

    positibe_cms.cms_extension:
        class: Positibe\Bundle\CmsBundle\Twig\Extension\PositibeCmsExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    positibe_cms.sitemaps_page_provider:
        class: Positibe\Bundle\CmsBundle\Sitemap\SitemapPageProvider
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: cmf_seo.sitemap.loader }

    positibe_cms.alternate_locale_provider:
        class: Positibe\Bundle\CmsBundle\Sitemap\AlternateLocaleProvider
        arguments: ["@cmf_routing.generator", "@request_stack"]

#### Forms Type ####
    positibe_cms.base_content_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\BaseContentType
        arguments: ["%locales%", "%locale%"]
        tags:
          - { name: form.type }

    positibe_cms.page_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\PageType
        arguments: ["@doctrine.orm.entity_manager", "%positibe_cms.available_controllers%",  "%positibe_cms.available_templates%"]
        tags:
          - { name: form.type }

    positibe_menu.menu_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\MenuType
        arguments: ["%positibe.menu_node.class%"]
        tags:
          - { name: form.type }

    positibe_menu.menu_node_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\MenuNodeType
        arguments: ["%positibe.menu_node.class%", "%locales%"]
        tags:
          - { name: form.type }

    positibe_cms.form.block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\AbstractBlockType
        tags:
            - {name: form.type }

    positibe_cms.form.content_block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\ContentBlockType
        arguments: ["%locales%"]
        tags:
            - {name: form.type }

#### Block Services ####
    positibe_cms.pages_by_category:
            class: Positibe\Bundle\CmsBundle\Block\Service\PagesByCategoryBlockService
            arguments: ['positibe_cms.pages_by_category', "@templating", "@doctrine.orm.entity_manager"]
            tags:
              - { name: sonata.block }

    positibe_cms.featured_page:
        class: Positibe\Bundle\CmsBundle\Block\Service\FeaturedBlockService
        arguments: ['positibe_cms.featured_page', "@templating", "@doctrine.orm.entity_manager"]
        tags:
            - {name: sonata.block }

    positibe_cms.block_page:
        class: Positibe\Bundle\CmsBundle\Block\Service\PageBlockService
        arguments: ['positibe_cms.block_page', "@templating", "@request_stack"]
        tags:
            - {name: sonata.block }
        calls:
            - [ setEm, ["@doctrine.orm.entity_manager"]]


    positibe_cms.block_content:
        class: Positibe\Bundle\CmsBundle\Block\Service\ContentBlockService
        arguments: ['positibe_cms.block_content', "@templating", "@request_stack"]
        tags:
            - { name: sonata.block }

    positibe_cms.block_gallery:
        class: Positibe\Bundle\CmsBundle\Block\Service\GalleryBlockService
        arguments: ['positibe_cms.block_gallery', "@templating", "@request_stack"]
        tags:
            - { name: sonata.block }

    positibe_cms.block_menu:
        class: Positibe\Bundle\CmsBundle\Block\Service\MenuBlockService
        arguments: ['positibe_cms.block_menu', "@templating", "@request_stack"]
        tags:
            - { name: sonata.block }

#### Services and Utils ####
    positibe.factory.page:
        class: Positibe\Bundle\CmsBundle\Factory\PageFactory
        arguments: ["@positibe.factory.menu", "@positibe_routing.route_factory", "@doctrine.orm.entity_manager", "%locale%"]

    positibe.factory.menu:
        class: Positibe\Bundle\CmsBundle\Factory\MenuNodeFactory
        arguments: ["@positibe.repository.menu"]
        tags:
            - { name: sylius.factory ,alias: positibe.factory.menu}