parameters:
    stof_doctrine_extensions.event_listener.locale.class: Positibe\Bundle\CoreBundle\EventListener\LocaleListener

services:
#### Forms Type ####
    positibe_cms.abstract_page_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\AbstractPageType
        arguments: ["@positibe_routing.route_factory", "%locales%", "%locale%"]
        tags:
          - { name: form.type , alias: positibe_abstract_page }

    positibe_cms.page_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\PageType
        arguments: ["@doctrine.orm.entity_manager", '@positibe_routing.route_factory', %locales%, %locale%]
        tags:
          - { name: form.type , alias: positibe_page }

    positibe_cms.category_form_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\CategoryType
        tags:
          - { name: form.type , alias: positibe_category }

    positibe_cms.form.visibility_block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\AbstractVisibilityBlockType
        tags:
            - {name: form.type, alias: positibe_block_visibility }

    positibe_block.form.page_block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\PageBlockType
        tags:
            - {name: form.type, alias: positibe_page_block }

    positibe_cms.form.content_block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\ContentBlockType
        arguments: [%locales%]
        tags:
            - {name: form.type, alias: positibe_cms_block }

    positibe_cms.form.gallery_block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\GalleryBlockType
        tags:
            - {name: form.type, alias: positibe_gallery_block }

    positibe_cms.form.menu_block_type:
        class: Positibe\Bundle\CmsBundle\Form\Type\MenuBlockType
        tags:
            - {name: form.type, alias: positibe_menu_block }

#### Block Services ####
    positibe_cms.block_category:
            class: Positibe\Bundle\CmsBundle\Block\Service\CategoryBlockService
            arguments: ['positibe_cms.block_category', "@templating", "@doctrine.orm.entity_manager"]
            tags:
              - { name: sonata.block }

    positibe_cms.block_page:
        class: Positibe\Bundle\CmsBundle\Block\Service\PageBlockService
        arguments: ['positibe_cms.block_page', "@templating", "@request_stack"]
        tags:
            - {name: sonata.block }
        calls:
            - [ setEm, ["@doctrine.orm.entity_manager"]]

    positibe_cms.block_featured_page:
        class: Positibe\Bundle\CmsBundle\Block\Service\FeaturedBlockService
        arguments: ['positibe_cms.block_featured_page', "@templating", "@doctrine.orm.entity_manager"]
        tags:
            - {name: sonata.block }

    positibe_cms.block_content:
        class: Positibe\Bundle\CmsBundle\Block\Service\ContentBlockService
        arguments: ['positibe_cms.block_content', "@templating", "@request_stack"]
        tags:
            - { name: sonata.block }

    positibe_cms.block_gallery:
        class: Positibe\Bundle\CmsBundle\Block\Service\GalleryBlockService
        arguments: ['positibe_cms.block_gallery', "@templating", "@request_stack"]
        tags:
            - { name: sonata.block }

    positibe_cms.block_menu:
        class: Positibe\Bundle\CmsBundle\Block\Service\MenuBlockService
        arguments: ['positibe_cms.block_menu', "@templating", "@request_stack"]
        tags:
            - { name: sonata.block }

#### Services and Utils ####
    positibe.factory.page:
        class: Positibe\Bundle\CmsBundle\Factory\PageFactory
        arguments: ["@positibe.factory.menu", "@positibe_routing.route_factory", "@doctrine.orm.entity_manager", %locale%]

    positibe.factory.menu:
        class: Positibe\Bundle\CmsBundle\Factory\MenuNodeFactory
        arguments: ["@positibe.repository.menu"]
        tags:
            - { name: sylius.factory ,alias: positibe.factory.menu}