parameters:
    stof_doctrine_extensions.event_listener.locale.class: Positibe\Bundle\CmfBundle\EventListener\LocaleListener

services:

#### Forms Type ####
    positibe_orm_content.abstract_page_form_type:
        class: Positibe\Bundle\OrmContentBundle\Form\Type\AbstractPageType
        arguments: [@positibe_orm_routing.route_factory, %locales%, %locale%]
        tags:
          - { name: form.type , alias: positibe_abstract_page }

    positibe_orm_content.page_form_type:
        class: Positibe\Bundle\OrmContentBundle\Form\Type\PageType
        arguments: [@doctrine.orm.entity_manager, @positibe_orm_routing.route_factory, %locales%, %locale%]
        tags:
          - { name: form.type , alias: positibe_page }

    positibe_orm_content.category_form_type:
        class: Positibe\Bundle\OrmContentBundle\Form\Type\CategoryType
        tags:
          - { name: form.type , alias: positibe_page_category }

    positibe_orm_block.form.static_content_media:
        class: Positibe\Bundle\OrmContentBundle\Form\Type\StaticContentBlockType
        arguments: [%block_locations%]
        tags:
            - {name: form.type, alias: positibe_static_content_block }

    positibe_orm_media.form.block_media:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\MediaBlockType
        arguments: [%block_locations%]
        tags:
            - {name: form.type, alias: positibe_media_block }

    positibe_orm_media.form.content_media_type:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\ContentBlockType
        tags:
            - {name: form.type, alias: positibe_content_block }

    positibe_orm_media.form.slideshow_media_type:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\SlideshowBlockType
        tags:
            - {name: form.type, alias: positibe_slideshow_block }

#### Block Services ####
    positibe_orm_content.block_category:
            class: Positibe\Bundle\OrmContentBundle\Block\CategoryBlockService
            arguments: ['positibe_orm_content.block_category', @templating, @doctrine.orm.entity_manager]
            tags:
              - { name: sonata.block }

    positibe_orm_content.block_static_content:
        class: Positibe\Bundle\OrmContentBundle\Block\StaticContentBlockService
        arguments: ['positibe_orm_content.block_static_content', @templating, @doctrine.orm.entity_manager]
        tags:
            - {name: sonata.block }

    positibe_orm_content.block_featured_page:
        class: Positibe\Bundle\OrmContentBundle\Block\FeaturedBlockService
        arguments: ['positibe_orm_content.block_featured_page', @templating, @doctrine.orm.entity_manager]
        tags:
            - {name: sonata.block }

#### Services and Utils ####
    positibe_orm_content.page_factory:
        class: Positibe\Bundle\OrmContentBundle\Factory\PageFactory
        arguments: [@positibe_orm_content.menu_node_factory, @positibe_orm_routing.route_factory, @doctrine.orm.entity_manager, %locale%]

    positibe_orm_content.menu_node_factory:
        class: Positibe\Bundle\OrmContentBundle\Factory\MenuNodeFactory

#### @todo hubicar en su lugar
    positibe_cmf.form.menu_block_type:
        class: Positibe\Bundle\OrmContentBundle\Form\Type\MenuBlockType
        tags:
            - { name: form.type, alias: positibe_menu_block }

    positibe_cmf.block_menu:
        class: Positibe\Bundle\OrmContentBundle\Block\MenuBlockService
        arguments: ['positibe_orm_block.block_menu', @templating, @knp_menu.menu_provider]
        tags:
            - { name: sonata.block }
        calls:
            - [ setContainer, [@service_container]]