sylius_resource:
    settings:
        sortable: true
        filterable: true
        paginate: $paginate
    resources:
        positibe.page:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\Page
                repository: Positibe\Bundle\CmsBundle\Repository\PageRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\PageType
        positibe.category:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\Category
                repository: Positibe\Bundle\CmsBundle\Repository\CategoryRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\CategoryType
        positibe.menu:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\MenuNode
                repository: Positibe\Bundle\CmsBundle\Repository\MenuNodeRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\MenuType
        positibe.block:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\Block
                repository: Positibe\Bundle\CmsBundle\Repository\BlockRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
        positibe.content_block:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\ContentBlock
                repository: Positibe\Bundle\CmsBundle\Repository\BlockRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\ContentBlockType
        positibe.gallery_block:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\GalleryBlock
                repository: Positibe\Bundle\CmsBundle\Repository\BlockRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\GalleryBlockType
        positibe.menu_block:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\MenuBlock
                repository: Positibe\Bundle\CmsBundle\Repository\BlockRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\MenuBlockType
        positibe.page_block:
            driver: doctrine/orm
            classes:
                model:      Positibe\Bundle\CmsBundle\Entity\PageBlock
                repository: Positibe\Bundle\CmsBundle\Repository\BlockRepository
                controller: Positibe\Bundle\CmsBundle\Controller\ResourceController
                form:       Positibe\Bundle\CmsBundle\Form\Type\PageBlockType
