positibe_category_crud:
    resource: |
        alias: positibe.category
        templates: PositibeCmsBundle:Category
        redirect: update
    type: sylius.resource
    
positibe_category_transition:
    path: /category/{id}/apply_transition
    methods: [POST]
    defaults:
        _controller: positibe.controller.category:applyTransitionAction
        _sylius:
            redirect: referer