positibe_submenu_child_create:
    path: /menus/{parent}/{name}/children/new
    methods: [GET, POST]
    defaults:
        _controller: positibe.controller.menu:createAction
        _sylius:
            template: PositibeOrmContentBundle:SubMenuChildren:create.html.twig
            form: positibe_menu_node
            factory:
                method: createNewChildByParentName
                arguments: [$parent, $name]
            redirect:
                route: positibe_submenu_child_update
                parameters: { parent: $parent, name: $name, child_name: resource.name }

positibe_submenu_child_index:
   path: /menus/{parent}/{name}/children
   methods: [GET]
   defaults:
       _controller: positibe.controller.menu:indexAction
       _sylius:
           template: PositibeOrmContentBundle:SubMenuChildren:index.html.twig
           sorting:
               position: asc
           criteria:
               parent: $name

positibe_submenu_child_update:
    path: /menus/{parent}/{name}/children/{child_name}/edit
    methods: [GET, PUT]
    defaults:
        _controller: positibe.controller.menu:updateAction
        _sylius:
            template: PositibeOrmContentBundle:SubMenuChildren:update.html.twig
            form: positibe_menu_node
            criteria:
                name: $child_name
            redirect:
                route: positibe_submenu_child_update
                parameters: { parent: $parent, name: $name, child_name: resource.name }

positibe_submenu_child_delete:
    path: /menus/{parent}/{name}/children/{child_name}
    methods: [DELETE]
    defaults:
        _controller: positibe.controller.menu:deleteAction
        _sylius:
            criteria:
                name: $child_name
            redirect:
                route: positibe_submenu_child_index
                parameters: { parent: $parent, name: $name }

positibe_submenu_child_move_up:
    pattern: /menus/{parent}/{name}/children/{child_name}/move-up
    methods: [PUT]
    defaults:
        _controller: positibe.controller.menu:moveUpAction
        _sylius:
            criteria:
                name: $child_name
            redirect: referer

positibe_submenu_child_move_down:
    pattern: /menus/{parent}/{name}/children/{child_name}/move-down
    methods: [PUT]
    defaults:
        _controller: positibe.controller.menu:moveDownAction
        _sylius:
            criteria:
                name: $child_name
            redirect: referer