positibe_page_index:
    path: /pages/
    defaults:
        _controller: "positibe.controller.page:indexAction"
        _sylius:
            template: PositibeCmsBundle:Page:index.html.twig
            criteria:
                host: "expr:service('session').has('active_website') ? [service('session').get('active_website')] : service('security.token_storage').getToken().getUser().getHosts()"

positibe_page_crud:
    resource: |
        alias: positibe.page
        templates: PositibeCmsBundle:Page
        except: ['index']
        redirect: update
    type: sylius.resource

positibe_page_create_by_category:
    path: /page/new/{parent}
    methods: [GET, POST]
    defaults:
        _controller: positibe.controller.page:createAction
        _sylius:
            redirect:
                route: positibe_page_update
                parameters: { name: resource.name }
            factory:
                method: createNewByParentName
                arguments: [$parent]

positibe_page_transition:
    path: /page/{id}/apply_transition
    methods: [POST]
    defaults:
        _controller: positibe.controller.page:applyTransitionAction
        _sylius:
            redirect: referer